### ISSUE TITLE
deliver software contents locally to preserve privacy

### ISSUE THREAD

**Issue by anarcat** [gsliepen/ikistrap#1]
it should be possible, at least as an option, to deliver bootstrap content locally to preserve user's privacy. in the demo here, i need to load stuff from bootstrapcdn.com, ajax.googleapis.com and cloudflare.com.

**Comment by gsliepen** [comment]
On Tue, Mar 22, 2016 at 08:04:00AM -0700, anarcat wrote:

> it should be possible, at least as an option, to deliver bootstrap content locally to preserve user's privacy. in the demo here, i need to load stuff from bootstrapcdn.com, ajax.googleapis.com and cloudflare.com.

You are right. I will add an option for that. I'm thinking of making a
plugin as well to provide some extra features. I could have that one
automatically download and install the latest CSS and JS files locally.
I should also add rel="noreferrer" to the links in the header to improve
the privacy even if the files are not delivered locally.

## 

Met vriendelijke groet / with kind regards,
     Guus Sliepen guus@tinc-vpn.org

**Comment by gsliepen** [comment]
If you enable the ikistrap plugin, you can set `bootstrap_local: 1` in ikiwiki.setup.
This will expect all the required files in the css/, js/ and fonts/ directories.
If they are not there, they will be downloaded automatically.

**Comment by anarcat** [comment]
great, thanks!
