### ISSUE TITLE
keeps redownloading css files

### ISSUE THREAD

**Issue by xloem** [gsliepen/ikistrap#4]
The referenced css files do not render properly on Freenet.  I patched them locally, using `bootstrap_local: 1`, but ikistrap keeps redownloading them every update, and overwrites my changes.

**Comment by nicoonoclaste** [comment]
@xloem I cannot reproduce the issue.

I have as symlink in place, instead of the CSS files (that point to my local clone of Bootstrap), and it was never overwritten by ikistrap.

**Comment by xloem** [comment]
Thanks for checking this.  I've looked into it more in depth here, and it turns out it was a bug on my end elsewhere.  I'm sorry for this.
